### ISSUE TITLE
WyzeHMS.js TypeError: this.getCharacteristic is not a function

### ISSUE THREAD

**Issue by bunnyc1986** [jfarmer08/homebridge-wyze-smart-home#207]
**Describe The Bug:**
Inifinte crash and restart loop.

**Expected behavior:**
Should not crash.

**Logs:**

```
[1/31/2024, 7:29:16 PM] Homebridge v1.7.0 (HAP v0.11.1) (Wyze) is running on port 55859.

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46
      this.getCharacteristic(Characteristic.On).updateValue(noResponse);
           ^
TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46:12)
    at WyzeHMS.update (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:91:12)
    at WyzeSmartHome.loadDevice (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:157:15)
    at WyzeSmartHome.loadDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:117:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:106:7)
    at WyzeSmartHome.runLoop (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:90:9)
[1/31/2024, 7:29:17 PM] [Wyze] Child bridge process ended
```

**Plugin Config:**

```json
{
    "name": "Wyze",
    "username": "....",
    "password": "...",
    "keyId": "...",
    "apiKey": "...",
    "mfaCode": "...",
    "refreshInterval": 60000,
    "entryExitDelay": 30,
    "showAdvancedOptions": true,
    "logging": "none",
    "excludeMacAddress": true,
    "filterByMacAddressList": [
        "..."
    ],
    "excludedeviceType": false,
    "_bridge": {
        "username": "...",
        "port": ...
    },
    "platform": "WyzeSmartHome"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.5.37-alpha.7
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.11.0
* **NPM Version**: 10.2.4
* **Operating System**: Ubuntu (20.04.5 LTS)

**Comment by chris001** [comment]
Seems this crash bug's related to the `/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46` = Wyze Home Monitoring Service?

**Comment by bunnyc1986** [comment]
> Seems this crash bug's related to the `/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46` = Wyze Home Monitoring Service?

yes, I believe so.

**Comment by jfarmer08** [comment]
Do you have any active account for HMS?

**Comment by jfarmer08** [comment]
if you don't use HMS or you don't have subscription then add "hms": false to your config.

**Comment by chris001** [comment]
> if you don't use HMS or you don't have subscription then add "hms": false to your config.

Thanks.  However, using HMS with HMS subscription.

**Comment by bunnyc1986** [comment]
yes. I have active HMS subscription and am using the HMS. This used to happen occasionally in the past, but recently became consistently, besides the on going authentication issue.

**Comment by asachs01** [comment]
Same here. Neither enabling or disabling fixes the issue:

```
[2/10/2024, 1:12:19 PM] TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46:12)
    at WyzeHMS.update (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:133:12)
    at WyzeSmartHome.loadDevice (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:158:15)
    at WyzeSmartHome.loadDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:118:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:107:7)
    at WyzeSmartHome.runLoop (/var/lib/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:91:9)
[2/10/2024, 1:12:19 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by jfarmer08** [comment]
Try clearing the accessory cache for it.

**Comment by chris001** [comment]
> Try clearing the accessory cache for it.

How?  Commands?  Menu item?

**Comment by bunnyc1986** [comment]
I found this error shown up when the HMS is offline. My HMS became offline often recently.

**Comment by bunnyc1986** [comment]
> > Try clearing the accessory cache for it.
> 
> How? Commands? Menu item?

it's in Homebridge settings. "Remove Single Cached Accessory".
<img width="884" alt="image" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/1644274/f9f106ba-6de4-4832-a0f5-01b63633b8fb">

**Comment by asachs01** [comment]
That seems to have done it for me.

**Comment by chris001** [comment]
Can  `wyze-smart-home` detect when this error happens (`WyzeHMS.js TypeError: this.getCharacteristic is not a function`), and automatically do the  "remove single cached accessory" thru code?

**Comment by bunnyc1986** [comment]
I still see this error after removing the cached accessory.
the timing corelates when HMS is offline in the wyze app.

**Comment by jfarmer08** [comment]
hopefully this helps https://github.com/jfarmer08/homebridge-wyze-smart-home/releases/tag/v0.5.44

**Comment by carTloyal123** [comment]
@bunnyc1986 is this resolved or are there still issues?

**Comment by bunnyc1986** [comment]
> @bunnyc1986 is this resolved or are there still issues?

I no longer see the error after upgrading to v0.5.44. Thank you!

**Comment by bunnyc1986** [comment]
this issue just came back:

```
[2/18/2024, 3:58:35 PM] [Wyze] Restarting Process...
[2/18/2024, 3:58:35 PM] [Wyze] Launched child bridge with PID 2440
[2/18/2024, 3:58:35 PM] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[2/18/2024, 3:58:35 PM] [Wyze] Loaded homebridge-wyze-smart-home v0.5.44 child bridge successfully
[2/18/2024, 3:58:35 PM] Loaded 9 cached accessories from cachedAccessories.xxxxxx
[2/18/2024, 3:58:35 PM] Homebridge v1.7.0 (HAP v0.11.1) (Wyze) is running on port xxxxxx.

/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46
      this.getCharacteristic(Characteristic.SecuritySystemCurrentState).updateValue(noResponse);
           ^
TypeError: this.getCharacteristic is not a function
    at WyzeHMS.updateCharacteristics (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeHMS.js:46:12)
    at WyzeHMS.update (/homebridge/node_modules/homebridge-wyze-smart-home/src/accessories/WyzeAccessory.js:133:12)
    at WyzeSmartHome.loadDevice (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:158:15)
    at WyzeSmartHome.loadDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:118:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WyzeSmartHome.refreshDevices (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:107:7)
    at WyzeSmartHome.runLoop (/homebridge/node_modules/homebridge-wyze-smart-home/src/WyzeSmartHome.js:91:9)
[2/18/2024, 3:58:36 PM] [Wyze] Child bridge process ended
[2/18/2024, 3:58:36 PM] [Wyze] Process Ended. Code: 1, Signal: null
```

**Comment by jfarmer08** [comment]
You can comment out that line until i can get a fix.

```//this.getCharacteristic(Characteristic.SecuritySystemCurrentState).updateValue(noResponse);```

**Comment by jfarmer08** [comment]
*Update from the 2.0 work-in-progress on the [`2.0.0` branch](https://github.com/jfarmer08/homebridge-wyze-smart-home/tree/2.0.0):*

The buggy line was `this.getCharacteristic(...)` instead of `this.securityService.getCharacteristic(...)`. That's been corrected in the current main branch and is part of the 2.0 release. Verified in [`src/accessories/WyzeHMS.js`](https://github.com/jfarmer08/homebridge-wyze-smart-home/blob/2.0.0/src/accessories/WyzeHMS.js).
